<?php

abstract class RoleName {
	const CONFIG_ADMIN = 'CONFIG_ADMIN';
	const TAG_ADMIN = 'TAG_ADMIN';
	const CATEGORY_ADMIN = 'CATEGORY_ADMIN';
	const LOG_ADMIN = 'LOG_ADMIN';
	const REDIRECT_ADMIN = 'REDIRECT_ADMIN';
	const TEMPLATE_ADMIN = 'TEMPLATE_ADMIN';
	const PAGE_ADMIN = 'PAGE_ADMIN';
	const GROUP_ADMIN = 'GROUP_ADMIN';
	const ACCOUNT_ADMIN = 'ACCOUNT_ADMIN';
	const IMAGE_ADMIN = 'IMAGE_ADMIN';
}
